export const stages = [
  {
    background: "#fdf6e3",
    textColor: "#1a1208",
    lines: [
      { text: "(Ting. Ting.)", voice: "direction" },
      { text: "(The phone vibrates on the table.)", voice: "direction" },
      { text: "(A message.)", voice: "direction" },
      { text: "(He picks it up.)", voice: "direction" },
      { text: '"Bro, I got the job!"', voice: "direction" },
      { text: "(He stares at the screen for a moment longer than necessary.)", voice: "direction" },
      { text: "Good for him.", voice: "cypher" },
      { text: "Another one made it.", voice: "nihilism" },
      { text: "And me?", voice: "cypher" },
      { text: "Still here.", voice: "nihilism" },
      { text: "Unemployed. Again.", voice: "cypher" },
      { text: "Another day.", voice: "cypher" },
      { text: "Another attempt.", voice: "cypher" },
      { text: "Another quiet opportunity to fail.", voice: "cypher" },
      { text: "At least you're still standing.", voice: "absurdism" },
      { text: "Standing on a carefully constructed pile of my own failures.", voice: "cypher" },
      { text: "I'm not even sure anymore if it's something to climb out of…", voice: "cypher" },
      { text: "Or something you're slowly getting buried under.", voice: "nihilism" },
    ]
  },
  {
    background: "#fff8e7",
    textColor: "#2a1f10",
    lines: [
      { text: "Ting. Ting.", voice: "direction" },
      { text: "Friend: Got the job. Party at my place?", voice: "direction" },
      { text: "Yeah, yeah. We should celebrate.", voice: "nihilism" },
      { text: "Unemployment.", voice: "nihilism" },
      { text: "Yet another day living off your family's money.", voice: "nihilism" },
      { text: "I think… maybe I shouldn't go today.", voice: "cypher" },
      { text: "Why not? It could be fun.", voice: "absurdism" },
      { text: "My best friend got the job.", voice: "absurdism" },
      { text: "And I could breathe some fresh air—", voice: "absurdism" },
      { text: "Cigarettes.", voice: "nihilism" },
      { text: "At least that way one conclusion is guaranteed.", voice: "nihilism" },
      { text: "And it comes with peace.", voice: "nihilism" },
      { text: "What should I do…?", voice: "cypher" },
      { text: "Well, cigarettes are bad.", voice: "absurdism" },
      { text: "But I might feel better for a while.", voice: "absurdism" },
    ]
  },
  {
    background: "#fffdf5",
    textColor: "#3a2a18",
    lines: [
      { text: "I think I should go. I'm sure he'll be happy to see me… and I might relax for a bit as well.", voice: "cypher" },
      { text: "This room is suffocating.", voice: "cypher" },
      { text: "Feels like I'm getting strangled in here.", voice: "cypher" },
      { text: "Better to be strangled here than out there.", voice: "nihilism" },
      { text: "What are you going to say to them?", voice: "nihilism" },
      { text: "Still achieved nothing?", voice: "nihilism" },
      { text: "How are you going to face them?", voice: "nihilism" },
      { text: "Your presence is insignificant to them.", voice: "nihilism" },
      { text: "How long are you going to avoid it?", voice: "absurdism" },
      { text: "One day you'll have to face them anyway.", voice: "absurdism" },
      { text: "Maybe they'll help you.", voice: "absurdism" },
      { text: "Help him?", voice: "nihilism" },
      { text: "That's all he's been doing.", voice: "nihilism" },
      { text: "Taking aid. Crawling over broken glass in hope.", voice: "nihilism" },
      { text: "Life has no meaning. There's no point.", voice: "nihilism" },
      { text: "Maybe that's the fun part.", voice: "absurdism" },
      { text: "One must imagine Cypher happy.", voice: "absurdism" },
      { text: "I just wanted to be happy.", voice: "cypher" },
      { text: "(He throws the phone onto the floor.)", voice: "direction" },
      { text: "He's happier when he smokes.", voice: "nihilism" },
    ]
  },
  {
    background: "#7a6a5a",
    textColor: "#ffffff",
    lines: [
      { text: "It's so hot in here.", voice: "cypher" },
      { text: "The sun is shining so harshly… maybe I should go outside.", voice: "cypher" },
      { text: "Should I go?", voice: "cypher" },
      { text: "Or should I not?", voice: "cypher" },
      { text: "I have to make up my mind.", voice: "cypher" },
      { text: "I have to make a decision.", voice: "cypher" },
      { text: "I have to decide whether to rot here…", voice: "cypher" },
      { text: "or make the decision to leave.", voice: "cypher" },
      { text: "(Music starts playing.)", voice: "direction" },
      { text: "Maybe you should fasten your shoelaces and dance on your own grave instead of becoming one.", voice: "absurdism" },
      { text: "Don't worry.", voice: "nihilism" },
      { text: "He'll handle the pressure of failure dancing on his coffin very well.", voice: "nihilism" },
      { text: "He's specialized in that.", voice: "nihilism" },
      { text: "I don't know what to do.", voice: "cypher" },
      { text: "(The room is quiet except for the music.)", voice: "direction" },
      { text: "(He reaches for a cigarette.)", voice: "direction" },
      { text: "(A lighter clicks.)", voice: "direction" },
      { text: "There we go.", voice: "nihilism" },
      { text: "Finally.", voice: "absurdism" },
      { text: "A decision.", voice: "nihilism" },
      { text: "A small one, but still.", voice: "absurdism" },
      { text: "I guess… this counts.", voice: "cypher" },
    ]
  },
  {
    background: "#3a3545",
    textColor: "#ffffff",
    lines: [
      { text: "(Smoke hangs in the air.)", voice: "direction" },
      { text: "(The sunlight begins to soften, stretching across the floor.)", voice: "direction" },
      { text: "It's quieter now.", voice: "cypher" },
      { text: "I'm sweating… but the breeze feels good.", voice: "cypher" },
      { text: "(He inhales from the cigarette.)", voice: "direction" },
      { text: "Told you.", voice: "nihilism" },
      { text: "It's good.", voice: "nihilism" },
      { text: "Exactly.", voice: "absurdism" },
      { text: "See? It can be.", voice: "absurdism" },
      { text: "Wait…", voice: "cypher" },
      { text: "You both agree?", voice: "cypher" },
      { text: "I'm just stating facts.", voice: "nihilism" },
      { text: "So am I.", voice: "absurdism" },
      { text: "That's new.", voice: "cypher" },
      { text: "Not really.", voice: "nihilism" },
      { text: "You just never noticed.", voice: "absurdism" },
      { text: "No… this feels different.", voice: "cypher" },
      { text: "You don't sound different anymore.", voice: "cypher" },
      { text: "Maybe we aren't.", voice: "nihilism" },
      { text: "Maybe we never were.", voice: "absurdism" },
      { text: "Then what was all that before?", voice: "cypher" },
      { text: "Noise.", voice: "nihilism" },
      { text: "Perspective.", voice: "absurdism" },
      { text: "And now?", voice: "cypher" },
      { text: "Now it's simple.", voice: "nihilism" },
      { text: "Now it's quiet.", voice: "absurdism" },
      { text: "Quiet feels wrong.", voice: "cypher" },
      { text: "You're just not used to it.", voice: "nihilism" },
      { text: "Or maybe you are.", voice: "absurdism" },
      { text: "(He exhales slowly.)", voice: "direction" },
      { text: "I can't tell who's speaking.", voice: "cypher" },
      { text: "You don't need to.", voice: "nihilism" },
      { text: "You never did.", voice: "absurdism" },
    ]
  },
  {
    background: "#1a1525",
    textColor: "#ffffff",
    lines: [
      { text: "(The light fades from the room.)", voice: "direction" },
      { text: "(Shadows stretch. The walls feel distant.)", voice: "direction" },
      { text: "It's getting dark.", voice: "cypher" },
      { text: "Finally.", voice: "nihilism" },
      { text: "It's calmer now.", voice: "absurdism" },
      { text: "Why does it feel… easier?", voice: "cypher" },
      { text: "Because you stopped trying.", voice: "nihilism" },
      { text: "Because you stopped choosing.", voice: "absurdism" },
      { text: "Is that a good thing?", voice: "cypher" },
      { text: "It doesn't matter.", voice: "nihilism" },
      { text: "It never did.", voice: "absurdism" },
      { text: "(The cigarette burns down to ash.)", voice: "direction" },
      { text: "(He doesn't move.)", voice: "direction" },
      { text: "I thought something would change.", voice: "cypher" },
      { text: "It did.", voice: "nihilism" },
      { text: "You did less.", voice: "absurdism" },
      { text: "…", voice: "cypher" },
      { text: "(The room is silent.)", voice: "direction" },
      { text: "(Only the faint glow of the phone lights up his face.)", voice: "direction" },
      { text: "Ting. Ting.", voice: "direction" },
      { text: "(He looks at the screen.)", voice: "direction" },
      { text: '"Dude… gonna be a dad!!!"', voice: "direction" },
      { text: "Why do they even share these things with me?", voice: "cypher" },
      { text: "Another one.", voice: "nihilism" },
      { text: "Another day.", voice: "absurdism" },
      { text: "…", voice: "cypher" },
      { text: "(He stares at it.)", voice: "direction" },
      { text: "(No reaction.)", voice: "direction" },
      { text: "(The screen goes dark.)", voice: "direction" },
    ]
  },
  {
    background: "#050508",
    textColor: "#ffffff",
    lines: [
      { text: "", voice: "direction" },
    ]
  },
]